### ISSUE TITLE
Unable to compile the project ...

### ISSUE THREAD

**Issue by sbeex** [ArcBees/IDE-Templates#49]
Hello,
I tried to compile the project as Jar but I can't.

1) When I import the project in eclipse it is not recognized as a java project... what should I select ?

2)I generated the velocity-repack-7.jar or something like that. This works but what should I really do with that ? 

(Sorry but the doc is not really clear for me I am not an expert with Eclipse IDE)

Thank you in advance for your help ;)

**Comment by branflake2267** [comment]
You shouldn't have to touch the velocity lib. I had to hack and rebuild it
and that lib should be in the manifest already. I could try b later to
verify.

**Comment by branflake2267** [comment]
What I do is download the eclipse RCP build and then import existing
project. It should run after import.

**Comment by sbeex** [comment]
Hi Brandon, yes it works now. Thank you for your explainations I have to learn a bit how the code works now.

**Comment by branflake2267** [comment]
NP. Me too. Sorry I didn't provide more docs.  Good job!
