### ISSUE TITLE
com.arcbees.plugin.template.utils.VelocityUtils seems to be missing

### ISSUE THREAD

**Issue by meriouma** [ArcBees/IDE-Templates#56]
Hi Brandon! I was trying to update the idea plugin to intellij 14, and while toying around IDE-templates, I found that this class seems to be missing from the repository

**Comment by branflake2267** [comment]
Hm weird I'll have to check

**Comment by branflake2267** [comment]
I'd have to set things back up to see what was going on. I noticed it here tho, https://github.com/ArcBees/IDE-Templates/blob/54c7bcdfa4f1c72de90b57f2074ede68357787a1/src/test/java/com/arcbees/plugin/template/utils/VelocityUtils.java

**Comment by meriouma** [comment]
Ah! It's in the wrong source tree. Missed that! Thanks a lot!
